### ISSUE TITLE
userscripts.js: also link to each script's repo

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/charcoal-se.github.io#24]
The link to the raw source is convenient but if you want to find out more about the user script before installing it, being able to look at the README and perhaps even the code would be convenient, too.

I looked at userscript.coffee but this is not a platform I am familiar with. It's probably not hard for someone who knows what to change.

**Comment by j-f1** [comment]
The code for `userscripts.coffee` is [here](https://github.com/Charcoal-SE/charcoal-se.github.io/blob/site/_assets/js/userscripts.coffee), and here’s where the list items are generated:

https://github.com/Charcoal-SE/charcoal-se.github.io/blob/d95b457114547e27c705af39e323cdfb28bedc4e/_assets/js/userscripts.coffee#L52-L66

**Comment by fortunate-man** [comment]
@j-f1 yeah, I already found that, thanks! However, while building the website on my computer (macOS High Sierra), I get an error while executing the `script/build` script.

The complete traceback follows.

```
Force-fetching ms...
Force-fetching smokey...
fatal: repository 'https://@github.com/' not found
MS wiki commit:     [c752e29] Updated API Documentation (V2) (markdown)
Smokey wiki commit: [336538f] Added !!/ms-status
rm: _site/assets: No such file or directory
Configuration file: /Users/ashish/charcoal-se.github.io/_config.yml
bundler: failed to load command: jekyll (/usr/local/bin/jekyll)
ExecJS::RuntimeError: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.61.dylib
  Referenced from: /usr/local/bin/node
  Reason: image not found

  (execjs):1
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:219:in `exec_runtime'
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:39:in `exec'
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/external_runtime.rb:14:in `initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:44:in `eval'
  /usr/local/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/module.rb:23:in `eval'
  /usr/local/lib/ruby/gems/2.5.0/gems/autoprefixer-rails-7.1.6/lib/autoprefixer-rails/processor.rb:136:in `runtime'
  /usr/local/lib/ruby/gems/2.5.0/gems/autoprefixer-rails-7.1.6/lib/autoprefixer-rails/processor.rb:36:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/autoprefixer-rails-7.1.6/lib/autoprefixer-rails/sprockets.rb:20:in `run'
  /usr/local/lib/ruby/gems/2.5.0/gems/autoprefixer-rails-7.1.6/lib/autoprefixer-rails/sprockets.rb:14:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:23:in `block in call'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/utils.rb:200:in `dfs'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/bundle.rb:24:in `call'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:174:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:174:in `first'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:174:in `block in extra_assets'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:88:in `block in each_logical_path'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:114:in `block (2 levels) in logical_paths'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:228:in `block in stat_tree'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:212:in `block in stat_directory'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:209:in `stat_directory'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/path_utils.rb:227:in `stat_tree'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:105:in `block in logical_paths'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:104:in `logical_paths'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:83:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/sprockets-3.7.2/lib/sprockets/legacy.rb:83:in `each_logical_path'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:173:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:173:in `map'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:173:in `extra_assets'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:131:in `initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:42:in `new'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/env.rb:42:in `init'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-assets-2.4.0/lib/jekyll/assets/hooks/jekyll/setup.rb:8:in `block in <top (required)>'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:103:in `block in trigger'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/hooks.rb:102:in `trigger'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:104:in `reset'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/site.rb:33:in `initialize'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:30:in `new'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:30:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-livereload-0.2.2/lib/jekyll-livereload/build.rb:30:in `process'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /usr/local/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /usr/local/lib/ruby/gems/2.5.0/gems/jekyll-3.7.3/exe/jekyll:15:in `<top (required)>'
  /usr/local/bin/jekyll:23:in `load'
  /usr/local/bin/jekyll:23:in `<top (required)>'
script/build: line 66: pushd: _site: No such file or directory
script/build: line 67: pushd: assets: No such file or directory
cp: branding*.css: No such file or directory
cp: charcoal*.png: No such file or directory
script/build: line 77: popd: directory stack empty
script/build: line 103: popd: directory stack empty
```

Do you have any idea on what could be causing this?

**Comment by j-f1** [comment]
> `fatal: repository 'https://@github.com/' not found`
> `rm: _site/assets: No such file or directory`

This should be fixed by https://github.com/Charcoal-SE/charcoal-se.github.io/commit/62c615c5e0c247e6bbf8a4943ea1baa2a83283b1.

> `ExecJS::RuntimeError: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.61.dylib`

I’m not sure what caused this. Maybe try running `bundle` again?

**Comment by fortunate-man** [comment]
Alright, I'll try that out! Thanks!
